name: a1
version: 2.2.0

homepage: https://pub.dev/packages/a1
repository: https://github.com/sjhorn/a1
description: A package that implements A1 Notation used in spreadsheets and worksheets
screenshots:
  - description: 'A1 logo for A1 Notation'
    path: assets/a1_small.png
topics:
  - a1-notation
  - spreadsheet
  - worksheet
  - parsing

environment:
  sdk: ^3.3.0
dependencies:
  petitparser: ^7.0.1
dev_dependencies:
  lints: ^6.1.0
  test: ^1.24.0
